import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 🌐 Navigation Bar */}
        <nav className="w-full bg-black font-bold text-white px-6 py-4 flex gap-6 mx-auto justify-center">
          <Link href="/upload-email" className="hover:underline">
            Upload Emails
          </Link>
          {/*           <Link href="/generate" className="hover:underline">
            Generate response with custom text
          </Link> */}

          <Link href="/eml-reply" className="hover:underline">
              Find Thread and reply  
          </Link>
        </nav>

        {/* Page Content */}
        <main className="p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
